# -*- coding: utf-8 -*-
"""Personal Project: Modeling Financial Market

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fqs16yw6JO_wiEykQlEb5sDj78h1oJxt
"""

import yfinance as yf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error
import seaborn as sns

data = yf.download("AAPL", start="2020-01-01", end="2024-12-31")

data.columns

df = data [['Close']].dropna()
df.rename(columns={'Close': 'price'}, inplace=True)

df['return'] = df['price'].pct_change()
df.dropna(inplace=True)

df['price'].plot(title="AAPL Price History")

plt.title("Distribution of AAPL Daily Returns (2020-2024)")
plt.xlabel("Daily Returns")
plt.ylabel("Frequency")
sns.histplot(df['return'], bins=50, kde=True)
plt.show()

df['return'].describe(percentiles=[.05, .25, .5, .75, .95])

df['rolling_vol'] = df['return'].rolling(window=30).std()
df['rolling_vol'].plot(title="30-Day Rolling Volatility (APPL 2020-2024)")

df_reset = df.reset_index()
plt.scatter(x=df_reset['price'], y=df_reset['rolling_vol'])
plt.title("Price vs Volatility")
plt.xlabel("Price (USD)")
plt.ylabel("30-Day Volatility")
plt.show()

"""Summary:

**Price History:** The plot shows the trend of AAPL's closing price over the specified period. You can visually observe periods of increase and decrease.

**Daily Returns Distribution:** The histogram of daily returns shows how frequently different return percentages occurred. The peak around 0 indicates that most daily returns were close to zero. The tails of the distribution show the occurrences of larger positive and negative returns. The descriptive statistics provide specific values like the average daily return, standard deviation (volatility), and the range of returns (min and max).

**Rolling Volatility:** The 30-day rolling volatility plot illustrates how the stock's price fluctuation has changed over time. Peaks in this plot indicate periods of higher risk or uncertainty.

**Price vs Volatility:** The scatter plot shows the relationship between the stock price and its 30-day rolling volatility. This can help visualize if there's any correlation between the price level and how much the price is moving.




"""

df['target'] = df['price'].shift(-1)
df.dropna(inplace=True)

features = ['price', 'rolling_vol', 'return']
x = df[features]
y = df['target']

split = int(len(df)*0.8)
x_train, x_test = x.iloc[:split], x.iloc[split:]
y_train, y_test = y.iloc[:split], y.iloc[split:]

model = RandomForestRegressor(
    n_estimators=200,
    max_depth=10,
    random_state=42
)
model.fit(x_train, y_train)

preds = model.predict(x_test)
rmse = np.sqrt(mean_squared_error(y_test, preds))
print(f"Root Mean Squared Error (RMSE): ${rmse:.2f}")

plt.figure(figsize=(10,5))
plt.plot(y_test.values, label='Actual Prices', linewidth=2)
plt.plot(preds, label='Predicted Prices', linewidth=2)
plt.title("Random Forest Price Prediction (Next-Day Forecast)")
plt.xlabel("Days")
plt.ylabel("Price (USD)")
plt.legend()
plt.show()

from sklearn.metrics import r2_score
r2 =r2_score(y_test, preds)
mape = np.mean(np.abs((y_test - preds) / y_test)) * 100

print(f"Root Mean Squared Error (RMSE): ${rmse:.2f}")
print(f"R^2 Score: {r2:.2f}")
print(f"Mean Absolute Percentage Error (MAPE): {mape:.2f}%")

importances = model.feature_importances_
feat_importance = pd.DataFrame({'Feature': features, 'Importance': importances})
feat_importance = feat_importance.sort_values(by='Importance', ascending=False)

plt.figure(figsize=(6,4))
sns.barplot(x='Importance', y='Feature', data=feat_importance, palette='viridis')
plt.title("Feature Importance (Random Forest)")
plt.xlabel("Relative Importance")
plt.ylabel("Feature")
plt.show()

residuals = y_test - preds

plt.figure(figsize=(8,4))
sns.histplot(residuals, bins=40, kde=True)
plt.title("Residual Distribution (Actual - Predicted)")
plt.xlabel("Prediction Error (USD)")
plt.ylabel("Frequency")
plt.show()